id: book_settings
label: Book configuration
migration_tags:
  - Drupal 6
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - book_child_type
    - book_allowed_types
  source_module: book
process:
  child_type: book_child_type
  allowed_types: book_allowed_types
destination:
  plugin: config
  config_name: book.settings
