ckeditor5.plugin.ckeditor_font_font:
  type: mapping
  label: 'Font Family'
  mapping:
    supportAllSizeValues:
      type: boolean
      label: 'Support all values'
    supportAllFamilyValues:
      type: boolean
      label: 'Suport all values'
    font_names: 
      type: sequence
      label: 'Font families'
      sequence:
        type: string
        label: 'Font family'
    font_sizes: 
      type: sequence
      label: 'Font sizes'
      sequence:
        type: ckeditor5.plugin.ckeditor_font_font.allowAllSize.[%parent.%parent.supportAllSizeValues]
ckeditor5.plugin.ckeditor_font_font.allowAllSize.0:
  type: mapping
  label: 'Font size'
  mapping:
    title:
      type: label
      label: 'Font size label'
    model:
      type: string
      label: 'Font size value'
ckeditor5.plugin.ckeditor_font_font.allowAllSize.1:
  type: integer
  label: 'Font size integer value'
ckeditor5.plugin.ckeditor_font_font_color:
  type: mapping
  label: 'Font Color'
  mapping:
    font_colors: 
      type: string
      label: 'Colors'
    columns:
      type: integer
      label: 'Columns'
    documentColors:
      type: integer
      label: 'Maximum available colors'
ckeditor5.plugin.ckeditor_font_font_background_color:
  type: mapping
  label: 'Font Background Color'
  mapping:
    font_backgroundcolors: 
      type: string
      label: 'Colors'
    columns:
      type: integer
      label: 'Columns'
    documentColors:
      type: integer
      label: 'Maximum available colors'